### ISSUE TITLE
Latex: hyperref does not produce working bookmarks for sections (first level elements)

### ISSUE THREAD

**Issue by matsch-o0** [sigchi/Document-Formats#52] opened 2015-09-18 23:45 UTC
Building the sample file proceedings.tex (or any derivative thereof) does not produce working PDF bookmarks for sections (first level elements). Looking closer into the issue in Acrobat reveals that the used destination name has different casing than the actual destination name. For example, the bookmark for the Introduction section points to the destination "section*.4", whereas the actual destination for the Introduction section is "SECTION*.4". Manually changing the destination for each section in Acrobat solves the issue. However, this should obviously be automatic.

I looked into the sigchi.cls, but this is about where my Latex foo ends. Didn't find a fix other than manually fixing bookmarks in Acrobat.

**Comment by ayman** [comment] 2015-09-19 00:15
Duplicate of https://github.com/sigchi/Document-Formats/issues/49

**Closed as completed by ayman** 2015-09-19 00:15 UTC
Labels: duplicate
