### ISSUE TITLE
year appears in the reference twice

### ISSUE THREAD

**Issue by jeffhuang** [sigchi/Document-Formats#41] opened 2015-08-07 22:21 UTC
The CHI LaTeX reference format seems to put the year in the reference twice. In the example LaTeX pdf, we see:

Anna Cavender, Shari Trewin, and Vicki Hanson. 2014. Accessible Writing Guide. (2014). http://www.sigaccess.org/welcome- to- sigaccess/ resources/accessible- writing- guide/.

Jofish Kaye and Paul Dourish. 2014. Special issue on science fiction and ubiquitous computing. Personal and Ubiquitous Computing 18, 4 (2014), 765–766. DOI: http://dx.doi.org/10.1007/s00779- 014- 0773- 4

Seems a bit redundant. Is this intentional, or something that should be fixed?

**Comment by ayman** [comment] 2015-08-08 21:47
Interesting.  Technically not a bug per se as that's in the ACM spec: 

http://www.acm.org/publications/article-templates/acm-latex-style-guide

See this ACM Ref as an example.  

```
Patricia S. Abril and Robert Plant. 2007. The patent holder's dilemma: buy, sell, or troll?. 
Commun. ACM 50, 1 (January 2007), 36-44. 
DOI=10.1145/1188913.1188915 http://doi.acm.org/10.1145/1188913.1188915
```

@jofish Assigning it to you for a comment.

**Comment by jofish** [comment] 2015-08-17 17:43
I agree it feels a bit redundant, but that is what the ACM ref standard says. I'll bring this up with Bernie Rous as one of the things we'd like to see fixed at the ACM level. Let's keep it as it is.

**Comment by ayman** [comment] 2015-08-17 17:44
I'll double check the Word formats then close this ticket once done.

**Comment by jeffhuang** [comment] 2015-08-17 17:59
Most CHI references are other conference papers, and the ACM format according to that style guide is:

"For a (paginated proceedings) article in a conference proceedings (conference, symposium or workshop):

Sten Andler. 1979. Predicate Path expressions. In Proceedings of the 6th. ACM SIGACT-SIGPLAN symposium on Principles of Programming Languages (POPL '79). ACM Press, New York, NY, 226-236. DOI:http://dx.doi.org/10.1145/567752.567774"

which only shows the year once as "1979". The "POPL '79" is the series field in BibTeX.

**Comment by ayman** [comment] 2015-08-17 20:54
@jeffhuang The bst file that is in this repository is the official ACM bst file.  I made one edit for the number formatting.  The double year citations you mentioned at the start of this issue are not proceedings but the `article` and `misc` fields. `inproceedings` does not exhibit this behavior, from this example:

![image](https://cloud.githubusercontent.com/assets/1846/9316000/5b3ce2d6-44e7-11e5-96e5-3e5e3df3113f.png)

**Comment by luileito** [comment] 2015-08-18 09:58
I'd say it's not redundant if the month of the article was included in the BibTeX entry. However, for some articles (especially the old ones) it's difficult to get the month of publication and even the full name of the authors. :disappointed:

**Comment by ayman** [comment] 2015-08-18 16:15
We did edit the template to tell people the First name is encouraged but
optional and just do what you can as we realize not everything is fully
available.

**Closed as completed** 2015-08-24 00:43 UTC
