### ISSUE TITLE
Error citing a website: Undefined control sequence

### ISSUE THREAD

**Issue by s-tikhomirov** [sigchi/Document-Formats#110] opened 2018-03-10 19:01 UTC
Here is a minimal example.

.tex:

```
\documentclass{sigchi}
\begin{document}
	A sample citation~\cite{ExampleWebsite}.
	\bibliographystyle{SIGCHI-Reference-Format}
	\bibliography{bug}
\end{document}
```

.bib:

```
@misc{ExampleWebsite,
	author    = {},
	title     = {Example},
	note      = {\url{http://example.org/}},
	urldate   = {2018-01-01}
}
```

Result:

![screenshot from 2018-03-10 19-58-55](https://user-images.githubusercontent.com/7126627/37245772-908d400a-249d-11e8-914a-ba96ee9545f0.png)

Error message:

```
! Undefined control sequence.
\UrlFont ->\color 
                  {black}\small \bf \ttfamily 
l.40 \shownote{\url{http://example.org/}.}
                                          
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.
```

**Comment by sven-mayer** [comment] 2018-03-11 23:14
I would argue that URLs are not scientific references anyway and should be placed as a footnote and therefore the issue is not relevant and can be closed.

**Comment by alialkhatib** [comment] 2018-03-12 00:27
My understanding is that footnotes usually serve as explanatory notes (which may only be a url, or may be a whole digression), whereas references are more often used either as "proof" of some claim being made (e.g. "something happened, causing a great deal of controversy [1, 2, 3, 4].") or to explicitly point an idea being referenced (e.g. "this system embodies the Foucauldian conceptualization of the panopticon [4].")

This is admittedly a different slice than you're taking, but I worry that if we cut according to what's formal scholarship and what's not, then this categorical difference could lead to situations where we're pointing to scholarly and non-scholarly sources and writing things like "something happened, and it was controversial [1, 2, also see footnotes 1 and 2]" despite all four of those pointers being thematically the same - "evidence of the claim being made". Whether that's a real problem is honestly a matter of personal preference, so I won't really argue it except to point out that it might frustrate people.

Out of interest, I skimmed the "Best Papers" from last year's CHI proceedings, and something like two thirds of those papers used the references section to point to sources not meant to be interpreted as scholarly - forums and other websites - just as they cited scholarship (I only looked at 25, so if that wasn't exhaustive, my bad). I'm wary of pointing to BPs and saying we should do everything they do without question, but my intuition is that if reviewers were bothered by this practice, we wouldn't see them giving BP awards to so many papers engaging in it.

All of this is to say that a norm seems to have emerged, and I'm reluctant to tell people their practice is wrong if they're doing something that good papers do, unless we get clear guidance from SIGCHI or ACM to express that point of view through the document template.

**Comment by alialkhatib** [comment] 2018-03-12 00:37
Ah, @s-tikhomirov , usually when I cite websites I use a format like this:

```
@misc{bibtexKey,
  author             = {lastname, firstname},
  title              = {title here},
  month              = {month},
  year               = {year},
  url                = {https://foo.bar},
}
```

I haven't had any problems. Maybe the issue is assigning it to the `note` parameter? When I cite

```
@misc{whoareNOTtheTurkers,
  author             = {Silberman, Six},
  title              = {Stop citing Ross et al. 2010, ``Who are the crowdworkers?"},
  month              = {3},
  year               = {2015},
  url                = {https://medium.com/@silberman/stop-citing-ross-et-al-2010-who-are-the-crowdworkers-b3b9b1e8d300},
}
```

I get this (which is what I want)

<img width="314" alt="screen shot 2018-03-11 at 5 37 08 pm" src="https://user-images.githubusercontent.com/1772301/37260642-e894008a-2552-11e8-8eed-f90096364b66.png">

**Comment by s-tikhomirov** [comment] 2018-03-12 11:46
@alialkhatib , I avoided my problem by replacing `note = \url{example.org}` with `note = {example.org}`:

![screenshot from 2018-03-12 12-42-31](https://user-images.githubusercontent.com/7126627/37281933-e9797e3a-25f2-11e8-880e-ee97cae1b125.png)

A drawback is that the URL is not in typeface font. And I don't why the year is repeated twice.

My particular problem aside, I'd argue that the initial behavior is still a bug. If the style doesn't allow or encourage URLs in references, it should be mentioned explicitly, not through a weird error which seems to be due to a missing space somewhere (`blackhttp.example.org`).

**Closed as completed** 2019-12-12 19:49 UTC
Labels: wontfix
